dashbase/ansible/roles/telegraf/templates/telegraf.yml.j2
dashcomm/ansible/roles/telegraf/templates/configs/freeswitch_nw.yml
dashcomm/ansible/roles/telegraf/templates/telegraf.yml.j2
dashcomm/standalone-configs/README.md
dashcomm/standalone-configs/freeswitch-nw.yml
dashcomm/standalone-configs/telegraf.conf

add standalone configs for Telegraf and night-watch in DAFS.

add more standalone configs

---

dashbase/ansible/roles/filebeat/templates/filebeat.yml.j2
dashcomm/ansible/roles/filebeat/templates/filebeat.yml.j2
dashcomm/standalone-configs/filebeat.yml

Ref: https://dashbase.atlassian.net/browse/DB-175

add hostname in filebeat processors

---

dashcomm/ansible/roles/filebeat/templates/configs/freeswitch.yml
dashcomm/ansible/roles/filebeat/templates/filebeat.yml.j2
dashcomm/standalone-configs/filebeat.yml

Ref: https://dashbase.atlassian.net/browse/DB-426

collect cdr info

---

dashcomm/ansible/roles/filebeat/templates/configs/freeswitch.yml
dashcomm/standalone-configs/filebeat.yml

Ref: https://dashbase.atlassian.net/browse/DB-425

extract sip log timestamp

---

dashbase/standalone-configs/README.md
dashbase/standalone-configs/app-nw.yml
dashbase/standalone-configs/filebeat.yml
dashbase/standalone-configs/freeswitch-nw.yml
dashbase/standalone-configs/telegraf.conf

Copy and modify from `dashcomm` standalone configs.

Dashbase standalone configs

---

dashbase/kubernetes/dashbase-collector.reference.yml
dashbase/kubernetes/dashbase-collector.yml

Remove extra protocol to make doc https://dashbase.atlassian.net/wiki/spaces/EngInternal/pages/414188554/---Getting+Data+Into+Dashbase+From+Kubernetes+Hosts+1.0 more simple.

remove protocol in filebeat configuration

---

dashbase/ansible/roles/filebeat/templates/configs/syslog.yml

Fixed syslog timestamp grok pattern

Example parsing configuration for kamailio

---

dashbase/monitoring/alerts-template/Chart.yaml
dashbase/monitoring/alerts-template/templates/alerts.yaml
dashbase/monitoring/generate_prometheus_rules.sh
dashbase/monitoring/prometheus-alerts/api.yml
dashbase/monitoring/prometheus-alerts/collection-alerts.yml
dashbase/monitoring/prometheus-alerts/etcd.yml
dashbase/monitoring/prometheus-alerts/k8s.yml
dashbase/monitoring/prometheus-alerts/kafka.yml
dashbase/monitoring/prometheus-alerts/proxy.yml
dashbase/monitoring/prometheus-alerts/table.yml
dashbase/monitoring/prometheus-alerts/version.note
dashbase/monitoring/prometheus-alerts/web.yml
dashbase/monitoring/prometheus-alerts/zookeeper.yml
dashbase/monitoring/prometheus-operator-rules/api.yml
dashbase/monitoring/prometheus-operator-rules/collection-alerts.yml
dashbase/monitoring/prometheus-operator-rules/etcd.yml
dashbase/monitoring/prometheus-operator-rules/k8s.yml
dashbase/monitoring/prometheus-operator-rules/kafka.yml
dashbase/monitoring/prometheus-operator-rules/proxy.yml
dashbase/monitoring/prometheus-operator-rules/table.yml
dashbase/monitoring/prometheus-operator-rules/web.yml
dashbase/monitoring/prometheus-operator-rules/zookeeper.yml

Work with https://github.com/dashbase/dashbase/pull/321

Add prometheus rules generator

---

dashbase/ansible/roles/filebeat/templates/configs/freepbx.yml

add log config for FreePBX

---

collector-check/check_collector_status.sh

updated the check_collector_status.sh script to support systemd and sysvinit

updated the check_collector_status.sh script to support systemd and sysvinit

---

dashbase/values.reference.yaml

update description for `MAX_BUFFER_SIZE_MB`, `MAX_BUFFER_DELAY_IN_SEC` and `REALTIME_FREQUENCY_IN_SEC`

update description for segment flush setting

---

configs/dashcomm/values.yml

Add presto enable option in dashcomm default values.yml.

Add presto enable option

---

dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh

updated dashbase-installer script yaml file and tar file download path from S3 bucket to github.
no changes on script structure

DB-703 simplify dashbase installation.. updated download path 

---

log-collection/parsing-tools/tests/test_asterisk.py

Added unit tests.
Pushkars-MacBook$ ./unittest.sh 
..........
----------------------------------------------------------------------
Ran 10 tests in 0.001s
OK

Added unit tests

---

README.md
deployment-tools/update-license.sh

Merge upgrade license script from https://github.com/dashbase/dashbase-installation/pull/67

Merge upgrade license

---

deployment-tools/update-license.sh
deployment-tools/upgrade-dashbase.sh

1. added new upgrade-dashbase.sh script to upgrade dashbase version via admin pod.
2. fixed some typo in update-license.sh script
3. update the README.md for the instruction in upgrade-dashbase.sh script

DB-999 dashbase upgrade script

---

README.md
create-aws-eks.sh

Change in this PR
1. created a new script "create-aws-eks.sh" for simplify EKS cluster creation on AWS
2. updated the README.md file

DB-1031 Simplify  AWS EKS cluster installation

---

dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh

changes on this PR
1. To fix the issue when using ingress flag on dashbase-installer.sh script; the external IP address of the ingress controller is not displayed in the final output.

DB-1040 missing ingress controller  IP when using ingress flag 

---

deployment-tools/uninstall-dashbase.sh
deployment-tools/upgrade-dashbase.sh

1. Fix issue on uninstall script when dashbase  deployment has ingress controller 
2. Fix output message on entered image version for upgrade-dashbase.sh script

DB-1073 uninstall script stunk on uninstall dashbase

---

log-collection/ansible/roles/filebeat/templates/configs/freeswitch.yml

Relate to https://github.com/dashbase/dashbase-deployment/pull/618
https://dashbase.atlassian.net/browse/DB-1074

[DB-1074] Set sip call-id sortedFields.

---

dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh

1. only change in the default dashbase version from 1.1.0-rc1 to 1.1.0-rc2

change install script default version from 1.1.0-rc1 to 1.1.0-rc2

---

log-collection/ansible/roles/filebeat/templates/configs/freeswitch.yml

See comments in https://dashbase.atlassian.net/browse/DB-1294

DB-1294 fix freeswitch sip timestamp format

---

dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh

change the default version in dashbase-installer.sh and dashbase-installer-smallsetup.sh from 1.2.1 to 1.2.3

updated the installer script default version from 1.2.1 to 1.2.3

---

deployment-tools/uninstall-dashbase.sh

1. update the uninstall-dashbase.sh script to support removal of dashbase via manual helm installation

DB-1344 new uninstall dashbase script

---

deployment-tools/mydash-s3.json
deployment-tools/setup-s3-4v2.sh

1. added mydash-s3.json file which is an S3 bucket policy that grant R/W access to the s3 bucket that is created for V2 during installation
2. added  setup-s3-4v2.sh script that is the bash script that can do
- s3 bucket creation
- create s3 bucket policy base on mydash-s3.json template
- attach the s3 bucket policy to the EKS worker nodegroup instance role.
Both mydash-s3.json and  setup-s3-4v2.sh script is not invoked by circleci; and designed for manual V2 installation process

added mydash-s3.json setup-s3-4v2.sh files

---

deployment-tools/config/dashbase-metrics.yaml

changes in this PR added dashbase-metrics.yaml file which is a clone file for dashbase-exporter.yaml file for manual exporter testing

added dashbase-metrics.yaml file which is modified for exporter

---

aws_eks_dashbase_install_w_helm3.sh
deployment-tools/config/admindash-sts_helm3.yaml
deployment-tools/dashbase-admin/Dockerfile
deployment-tools/dashbase-installer-smallsetup_helm3.sh
deployment-tools/uninstall-dashbase.sh

Changes in this PR  is for DB-1374 . 
new file:   aws_eks_dashbase_install_w_helm3.sh
new file:   deployment-tools/config/admindash-sts_helm3.yaml
modified:   deployment-tools/dashbase-admin/Dockerfile
new file:   deployment-tools/dashbase-installer-smallsetup_helm3.sh
modified:   deployment-tools/uninstall-dashbase.sh
1. update aws eks creation script
2. update dashbase small setup to support helm3
3. update admindash docker image to install with helm 3.1.1
4. update admin pod yaml file admindash-sts_helm3.yaml
5. update dashbase uninstall script to support both cases of helm2 and helm3

DB-1374 update and etst install script to support helm3

---

aws_eks_dashbase_install.sh
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/setup-s3-4v2.sh

-- renamed dashbase-installer-smallsetup_helm3.sh script to dashbase-installer-smallsetup.sh 
-- updated aws_eks_dashbase_install.sh script to use update smallsetup script name
-- updated setup-s3-4v2.sh script to make it able to run repeatedly even when s3 bucket and s3 bucket policy was previously being created

renamed dashbas-installer-smallsetup.sh script removing helm3 suffix

---

dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/dashbase-installer-smallsetup_helm3.sh

update the admin pod wait time from 60 to 180 seconds on dashbase installer script

increase the wait time (from 60 to 180 seconds) for admin pod to come up

---

log-collection/ansible/roles/filebeat/templates/configs/portaone.yml

Modified from the config file provided in DB-1539
Tested locally and can see the SIP diagram on insights page now.

DB-1539 Extract ip address

---

dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/dashbase-installer-tinysetup.sh

changes in this PR, update line 577  to fix table variable bug failed to replace with sed command

update dashbase-installer to fix table variable bug

---

.gitattributes
.gitignore
log-collection/ansible/roles/logstash/files/logstash-oss-7.6.1.deb
log-collection/ansible/roles/logstash/tasks/main.yml

Verified on Ubuntu 16.04 with Ansible 2.0.0.2
ref: https://docs.ansible.com/ansible/latest/modules/get_url_module.html#parameters

DB-1532 Embed download logstash deb file

---

deployment-tools/config/dashbase-values-remote-poc.yaml
deployment-tools/config/dashbase-values-remote-test.yaml
deployment-tools/config/dashbase-values-remote.yaml
deployment-tools/config/etcd-headless.yaml

-- Added remote table yaml files for manual remote table setup
-- Added etcd headless yaml file to expose etcd stateful pod internal IP address

added remote v2 table yaml files

---

deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/tinysetup/dashbase-values.yaml
log-collection/ansible/roles/filebeat/templates/configs/freeswitch.yml
log-collection/ansible/roles/filebeat/templates/configs/heplify.yml
log-collection/windows/filebeat.yml
log-collection/windows/filebeat_kiwi.yml

Keita advised on having two replicas of smaller size than one big one for performance. 
Removed unused table parameters
Updated windows filebeats with new rename fields

changed to 2 replicas of table on large setup, clean up

---

log-collection/ansible/roles/filebeat/templates/configs/kamailio.yml

fix kamailio config

---

hooks/post_push

ref: https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks

build nightly-xxx via dockerhub autobuilds

---

log-collection/ansible/roles/filebeat/templates/configs/heplify.yml

Verified on the parser test page.

DB-2466 update heplify pattern to read milliseconds from tmsec

---

log-collection/ansible/inventory

Reverts dashbase/dashbase-installation#249

Revert "provide default filebeat inventory file to be able to run ansible loc…"

---

log-collection/ansible/roles/filebeat/templates/configs/kazoo.yml

DB-2723 add filebeat freeswitch cdr configuration for kazoo

---

log-collection/ansible/roles/filebeat/templates/configs/kazoo.yml

DB-2731 exclude freeswitch sip logs for kazoo

---

log-collection/ansible/roles/filebeat/templates/configs/kazoo.yml
log-collection/ansible/tests/filebeat/configs/kazoo.yml

These fields are used in new API to attach application logs in diagram

DB-2742 add some metadata backend will use

---

log-collection/ansible/roles/filebeat/files/freeswitch_cdr_rotate.py
log-collection/ansible/roles/filebeat/tasks/freeswitch.yml
log-collection/ansible/roles/filebeat/tasks/main.yml

This cronjob will delete files under `/var/log/freeswitch/json_cdr` (with subdirectory) which is suffixed with `.cdr.json` AND older than `1 hour` every 10 minutes.

DB-2724 add freeswitch cdr script with cronjob to run

---

log-collection/ansible/roles/filebeat/templates/configs/viber.yml

1) configuration to parse signalling logs (heplify format).
2) configuration to parse augmented SGW application_log

Signalling and application log parsing configuration

---

log-collection/ansible/roles/filebeat/templates/configs/viber.yml

adding
dashbase.voip.app: SGW
capture.src.ip: '0.0.0.0'
capture.src.port: '0'
for SGW event.log

adding sgw app type

---

log-collection/ansible/deploy_logstash.yml
log-collection/ansible/roles/logstash/templates/configs/fscdr_1.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/homer_1.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/netsapiens_1.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/netsapiens_3.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/netsapiens_4.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/netsapiens_5.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/netsapiens_6.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/netsapiens_7.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/netsapiens_8.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/nscdr_1.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/nscdr_2.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/sascdr_1.logstash.conf.j2

Fixes for Jim at Skyswitch:
1) added paging to logstash queries with the default page size of 10000
2) added more netsapiens templates
3) made all logstash schedules to run every minute

Logstash paging

---

log-collection/ansible/roles/filebeat/templates/configs/syslog.yml
log-collection/ansible/tests/filebeat/configs/syslog.yml
log-collection/ansible/tests/filebeat/configs/teammate.yml

This simple configuration works for different types of SBC messages collected by syslog

Parsing configuration for maintel syslog-collected SBC data
