dashbase/dashbase-installation

dashbase/ansible/README.md
dashbase/ansible/deploy.yml
dashbase/ansible/roles/filebeat/templates/filebeat.yml.j2

Major changes:
1. Remove hardcoded `http` in Filebeat and `https` in `pushgateway_url`
2. Require users to input `dashbase_url` with protocol and schema. (Otherwise, filebeat will connect `9200` by default)
3. Update Filebeat processors to allow users not specify `_message_parser`.
Tested locally.

fix protocol and port issues with Filebeat and PushGateway; make _message_parser optional

---

collector-check/README.md
collector-check/check_collector_playbook.yml
collector-check/check_collector_status.sh

Added a diagnostic script that runs through the filebeat observability. the script will check filebeat, telegraf, crontab entry, filebeat port/url, telegraf port/url, pushgateway port/url.  The script output will be shown on screen, and append to /tmp/dashbase_collector_check.log  file.
** This PR doesn't involve any modification of any existing files in this repo

DB-474 added dashbase collector check script

---

verfiy-dashbase-resources.sh

Tested both on MacOS and Alpine Linux.
Example output:
```
bash-5.0# ./verify.sh
Checking Statefulsets pods...
pod/auth-0 condition met
pod/elasticsearch-0 condition met
pod/etcd-0 condition met
pod/grafana-0 condition met
pod/influxdb-0 condition met
pod/kafka-0 condition met
pod/prometheus-0 condition met
pod/table-filebeat-0 condition met
pod/web-0 condition met
pod/zookeeper-0 condition met
Checking Deployments...
deployment.extensions/api condition met
deployment.extensions/chaodebug-kube-state-metrics condition met
deployment.extensions/deployment condition met
deployment.extensions/ingress-nginx-ingress-controller condition met
deployment.extensions/ingress-nginx-ingress-default-backend condition met
Checking Ingress External IP...
Ingress: External IP is ready
```

DB-713 verify k8s resource running

---

dashbase/ansible/deploy.yml
dashbase/kubernetes/dashbase-collector.reference.yml
dashbase/kubernetes/dashbase-collector.yml

Upgrade filebeat to oss-6.8.5, v6.6.x has a memory leak issue that we've potentially ran into before at 8x8.

Upgrade filebeat to oss-6.8.5

---

deployment-tools/dashbase-admin/dashbase_setup_tarball/https_presto2.sh
deployment-tools/dashbase-admin/dashbase_setup_tarball/https_presto_v2.sh
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/https_presto2.sh

We don't need the $NAMESPACE of prefix now.
After merged this RP 
https://github.com/dashbase/dashbase-k8s/pull/215
Whatever release name we use, we can use static the CN 
**_presto-coordinator-0.presto-coordinator.$NAMESPACE.svc.cluster.local_**
refer: we can find more detail here 
https://github.com/dashbase/dashbase-k8s/blob/634ed4ef93f6f68ac495bfa88542b514affc3d5d/presto/templates/_helpers.tpl#L14

Remove presto CN prefix

---

deployment-tools/uninstall-dashbase.sh

Change in this PR is on the uninstall-dashbase.sh script
1. remove dashbase using  while loop and timeout after 8 minutes
2. remove presto  using  while loop and timeout after 8 minutes
This changes can minimize the race condition and remove adminpod before dashbase & presto are completely removed via helm commands in adminpod.

DB-1024 upgrade script allow downgrade, causing uninstall stuck

---

README.md
dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/upgrade-dashbase.sh

change on this PR is mainly to address on issues DB-1023, DB-1024, and DB-1040 and added improvement on dashbase version checking
DB-1023 -- command not found sometimes happens on upgrade-dashbase.sh script
DB-1024 -- upgrade script should not allow downgrade dashbase version
DB-1040 -- display grafana url when expose endpoints using ingress 
make  dashbase-installer.sh script default using dashbase version 1.1.0-rc1  
improve dashbase version checking for entered version string and verify with github registry
check dashbase version creation time stamp and disable upgrade using an older version of dashbase
By default if no version is specified  for dashbase-install script will use default 1.1.0-rc1
and if no version is specified  for upgrade-dashbase.sh script, will use current dashbase …

Fix on DB-1023, DB-1024, DB-1040

---

deployment-tools/upgrade-dashbase.sh

1. updated the upgrade-dashbase.sh script to support chart version flag when user entering devel e.g. --chartversion=devel .   And this will convert as helm option using "--devel"
In normal upgrade, chart version doesn't need to be provided; because it will automatically match with your dashbase version. However, if you want to try nightly dashbase version, and you can either use current chart version or use latest devel version by entering flags like below
--chartversion=current
or 
--chartversion=devel
Similarly when user entered a dashbase version e.g. 1.1.0-rc2 but want to keep using the current chart version, then it can be done as follows
--version=1.1.0-rc2  --chartversion=current

updated upgrade-dashbase.sh script support devel & current chart version during upgrade

---

dashbase-installer.sh

1.  fix missing dashbase version, the variable VERSION should be equal to DASHVERSION  when version is not specified. It was echo on the message but not explicitly defined.

fix missing default dashbase version when no input version specified

---

deployment-tools/setup_aws_cli.sh

1. Added setup_aws_cli,sh script ; and this script will install AWS cli and configure it with supplied acccess key.
2. The setup_aws_cli.sh script will install kubectl command.
The primary purpose of this script is to enable a generic centos box with aws cli and able to run 
1. aws eks commands
2. kubectl commands
With ability to run aws eks and kubectl commands; the centos box can use our dashbase install and upgrade scripts without any issue.

added setup aws cli script

---

deployment-tools/setup_aws_cli.sh

Changes is this PR
1. fix issue on getting clustername with region, was hardcode to us-west-2 and now is changed to $REGION

fixed typo on REGION variable from hardcoded REGION variable 

---

deployment-tools/setup_aws_cli.sh

1. Fix the issue on missing fail_if_empty function on setup_aws_cli.sh script.
without this function exit condition may be an issue when parsing the input parameters

Fix issue on missing fail_if_empty function on setup_aws_cli.sh

---

README.md
create-aws-eks.sh
deployment-tools/create-docker-helper.sh

1. modify the create-aws-eks.sh script to use docker volumes to backup AWS credential information
2. make a new create-docker-helper.sh script for recovering docker-helper container after dashbase installation due to the container exited or deleted.
3. Update the README.md file to support the new script create-docker-helper.sh

DB-1098 recover docker-helper after installation

---

centos_setup_eks_dashbase.sh
dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/remove_aws_eks.sh
deployment-tools/upgrade-dashbase.sh

1. fix two typo in remove_aws_eks.sh script
2. change all output log files or files caused by this script to /tmp folder

Fixing typo and output log to /tmp insteasd of current folder

---

dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh

updated dashbase version from 1.1.1 to 1.2.1  on the installation scripts: dashbase-installer.sh  and dashbase-installer-smallsetup.sh

change dashbase version from 1.1.1 to 1.2.1

---

deployment-tools/create-sslcerts.sh

change in this PR.
Added a new script under deployment tools  and is called create-sslcerts.sh 
The purpose of this script is to create dashbase  and presto keystore and store them in K8s as secrets and extract the keystore passwords in the output. The dashbase and presto keystore passwords are required to be updated in presto section in the values yaml file

added create-sslcerts.sh script

---

dashbase-installer.sh
deployment-tools/dashbase-installer-smallsetup.sh

update dashbase version from 1.2.3 to 1.2.4 on the dashbase-installer.sh and dashbase-installer-smallsetup.sh  script

updated default installer script version from 1.2.3 to 1.2.4

---

log-collection/ansible/roles/filebeat/tasks/Configure.yml

When using the pattern `%{DATA:timestamp:datetime:MMM ppd HH:mm:ss} (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource:meta} %{SYSLOGPROG}: %{WORD:level:meta}: \{%{DATA:method:meta}\} - \{%{DATA:call-id:meta}\}%{GREEDYDATA:message}`, Ansible will raise an error like:
```
failed: [18.182.3.99] (item=chaotest) => {"ansible_loop_var": "item", "changed": false, "item": "chaotest", "msg": "AnsibleError: template error while templating string: tag name expected. String: - type: log\n  paths:\n    - /var/log/ingress.log\n    - /var/log/egress.log\n  fields:\n    _message_parser:\n      type: multi\n      parsers_list:\n        - name: grok\n          config:\n            type: grok\n            pattern: |-\n              %{DATA:timestamp:datetime:MMM ppd HH:mm:ss} (?:%{SYSLOGFACILITY} …
```

fix the template issue

---

deployment-tools/config/dashbase-exporter.yaml

added dashbase-exporter.yaml file  under the deployment-tools/config folder.
this exporter yaml file is for manual exporter deployment purpose; eventually will not be needed when exporter included in the helm chart after 1.2 version

added dashbase-exporter.yaml file

---

log-collection/ansible/roles/filebeat/templates/configs/heplify.yml
log-collection/ansible/roles/filebeat/templates/configs/kamailio.yml

1. Use the same field name `capture.*` in heplify and kamailio sipdump in case of multiple capture tools are running to harvest SIP packets. (We'll need to concatenate those SIP packets via the same field name)
2. Make some fields from `sorted` to `text` to reduce unnecessary cost.

unify field name over SIP capture tools

---

log-collection/ansible/roles/filebeat/templates/configs/kamailio.yml

1. Add missing `\~`
2. According to the source code, the dumps data should start with `====================` and end with `||||||||||||||||||||`. Ref: https://github.com/kamailio/kamailio/blob/master/src/modules/sipdump/sipdump_mod.c#L209-L222
Tested on the web UI.

fix sipdump pattern

---

aws_eks_dashbase_install.sh
aws_eks_dashbase_install_w_helm2.sh

The issue in this PR is caused from change the default cluster node number from 3 to 2 in small setup.. 
update aws eks script in large cluster size setup, change default node number from 2 to 3

fix aws eks script -- node number issue on default large cluster setup

---

aws_eks_dashbase_install.sh
aws_eks_dashbase_install_w_helm2.sh

change in this PR
update aws eks script  section check input value for large cluster size worker node number.
default was set to 2 and wasn't be updated on last changes.

Fix large cluster size default node number from 2 to 3

---

deployment-tools/config/dashbase-metrics.yaml

Removed more complex metric queries from example.

make default dashbase-metrics yaml a count of errors

---

dashbase-installer.sh
deployment-tools/config/admindash-sts_helm3.yaml
deployment-tools/dashbase-admin/Dockerfile
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/dashbase-installer-smallsetup_helm3.sh
deployment-tools/dashbase-installer-tinysetup_helm3.sh

Background
the admin pod "admindash-0" used in our installer script and poc setup contains unnecessary dashbase custom values yaml file, originally is planned for a template in which customer may use it. And the real or active one used in deploying dashbase is on /data  folder. And because of two custom values yaml files issue; skyswitch folk use wrong one to edit and cause upgrade problem.
-- updated admindash docker container image from the Dockerfile.
-- updated the installer script to use new admindash docker image version "1.5"
-- updated the installer script to create sym link /dashbase/dashbase-values.yaml --> /data/dashbase-values.yaml

updated admin pod; remove unnecessary dashbase values yaml file

---

log-collection/ansible/roles/filebeat/templates/filebeat.yml.j2

filebeat version in dashbase-installation is 7.x so dropping 'offset' but keeping 'log.offset'

not drop log.offset - needed by DB-1465

---

log-collection/ansible/roles/filebeat/templates/configs/freeswitch.yml

Unitize SIP and CDR logs to have the same user agent field name.
(This field is used by exporter to draw metrics.

add user-agent field for freeswitch cdr logs

---

log-collection/ansible/roles/telegraf/tasks/Debian.yml
log-collection/ansible/roles/telegraf/tasks/RedHat.yml

modify the ansible playbook regarding implement cronjob to send metrics to pushgateway using curl. since pushgateway may be secured by fake cert, then we update the 2nd curl command with "-k" options
changed on RedHat.yml  and Debian.yml

DB-1603 fix filebeat metrics collection due to curl issue in cronjob

---

deployment-tools/telegraf-deployment-set/telegraf-config.yaml
deployment-tools/telegraf-deployment-set/telegraf-deployment.yaml

1. Added a telegraf deployment set yaml files; and the telegraf deployment set is particular configured with  
inputs -->  prometheus:9090/federate (contains dashbase key metrics)
outputs -->  wavefront proxy 
use this telegraf deployment set is primarily want to ship the dashbase key metrics time series data from prometheus to external analytic dashboard 
No other files are affected or changed besides the added file in this PR

Added telegraf deployment yaml files  relates to DB-1144

---

deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/tinysetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/tinysetup/dashbase-values.yaml

updated dashbase-values.yaml file for stanard / poc / tiny setup for 
-- retention days to be 7
-- exporter's filter  to  be "type:sip"

updated dashbase-values.yaml file for retention days 

---

deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values.yaml

updated memory requirement for GCE node that has only 60GB
so v1 table memory requirement changed from 60G to 52G

update memory requirement from 60G to 52G for v1 table in standard setup

---

log-collection/ansible/roles/filebeat/templates/configs/freeswitch.yml

remove the copy processor as our urldecode pipeline can decode from `variables.sip_user_agent` directly.

remove copy_fields processor

---

deployment-tools/config/admindash-sts_helm3.yaml
deployment-tools/dashbase-admin/Dockerfile
deployment-tools/dashbase-admin/docker-entrypoint.sh

-- update admindash-sts_helm3.yaml file to use new admin pod docker image that will have persistent dashbase repo even after admin pod is restarted.
-- updated Dockerfile for admin pod
-- updated docker-entrypoint.sh file for admin pod

DB-1759 fix dashbase repo missing on admin pod after restarted

---

log-collection/ansible/deploy_logstash.yml
log-collection/ansible/roles/logstash/tasks/main.yml
log-collection/ansible/roles/logstash/templates/configs/netsapiens.logstash.conf.j2

re-creates sql statement with the table name updated to the current date:
event_20200421, event_20200422, etc. This cron job also restarts logstash
and removes .logstash_jdbc_last_run* file so fetching starting from
first record in new table.
Restart of logstash is required for jdbc driver to re-read sql
statement to run on schedule.

added cron job that runs at 0 minutes, 0 hours every day and

---

log-collection/ansible/roles/logstash/tasks/main.yml

because this task is already defined in the file.
1. https://github.com/dashbase/dashbase-installation/blob/master/log-collection/ansible/roles/logstash/tasks/main.yml#L47-L52
2. https://github.com/dashbase/dashbase-installation/blob/master/log-collection/ansible/roles/logstash/tasks/main.yml#L74-L79

remove duplicated task

---

deployment-tools/upgrade-dashbase.sh

Changes in this PR is to fix the upgrade script failing in certain use cases.
1. Added "helm repo update" before running the helm upgrade command.
2. New chart version checking logic.. usually when we do helm upgrade we usually don't specify --version and automatically it will use the latest stable chart version"
The following is the logic to determine the dashbase chart version
`Case 1 user has not entered any chart version and dashbase version
Case 1A  no chart version entered and will use current  devel version
Case 1B  no chart version entered and will use current non devel version
Case 2 user has not entered any chart version but specify dashbase version
Case 2A no chart version entered and no matching dashbase version in dashbase helm repo, will use latest stable chart version
Case …

DB-1953 fix upgrade script failing on certain use cases

---

dashbase-installer.sh
deployment-tools/check-K8s-cpu-memory.sh
deployment-tools/check-K8s-nodes-resources-usage.sh
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/dashbase-installer-tinysetup.sh
deployment-tools/uninstall-dashbase.sh

The dashbase-installer.sh  (include small & tiny setup) requires to use "--v2" to define for V2 installation. However, if you use "--version=2.12" ; and it won't automatically switch to V2 installation. And this PR is to add the script logic to detect if user input "--version=2.x.x" ; and whenever the left most version number (VNUM) is greater than or equal to 2; then it automatically to switch to V2 setup instead of explicitly using "--v2" flag e.g. "--v2 --version=2.1.2" 
1. allowing "--version=2.x.x"  detection in script logic.
2. update uninstall-dashbase.sh script to remove demo "freeswitch" compoents.
3. added check K8s cpu and node resources script.
All script changes in this PR are tested.

Update installer script to support --version=2.x.x to install V2 

---

aws_eks_dashbase_install.sh
deployment-tools/config/admindash-server-sts_helm3.yaml
deployment-tools/create-sslcerts.sh
deployment-tools/uninstall-dashbase.sh

1. Update the aws_eks_dashbase_install.sh script to use "--version" flag instead of "--v2"
So when deploying v2 with aws eks script, user can specify --version=2.2.1
And by default, the script will detects what version being entered, if no version is entered, the default is 1.5.4
From the dashbase version, the script will create the AWS EKS worker nodes accordingly:
For V1 Poc setup, EKS nodes will be 2 X R5.xlarge
For V1 standard setup, EKS nodes will be 2X R5.2xlarge
For V2 Poc setup, EKS node will be 1 X C5.4xlarge
For V2 standard setup, EKS nodes will be 2X C5.4xlarge
2. updated the dashbase uninstall script to remove previous created K8s cluster role, and role bindings via dashbase helm install and installation script.
3. updated admindash-server-sts-helm3.yaml …

updates on aws eks, uninstall, and admin pod image

---

deployment-tools/config/admindash-server-sts_helm3.yaml

Roll back changes on admin pod image 
from latest 
dashbase/dashbase-admin-server:nightly
to previous 
dashbase/dashbase-admin:chaotest
Because the latest image is missing some env variables, keytool, and openssl package which cause errors when running dashbase installation.

change admin pod image back to previous version

---

log-collection/ansible/roles/logstash/templates/configs/sascdr_1.logstash.conf.j2

Added two patterns here because `time_start` is `2020-07-14T08:46:48.000Z` on demo cluster, but become `2020-07-14 08:46:48` on sample logs.

DB-2259 fix sascdr date pattern

---

log-collection/ansible/roles/logstash/templates/configs/sascdr_1.logstash.conf.j2

rename `time_start` to `sas_time_start` to avoid schema flipping.

rename sas time_start

---

log-collection/ansible/roles/filebeat/templates/configs/kamailio.yml

DB-2298 use time as timestamp in kamailio logs

---

aws_eks_dashbase_install.sh
dashbase-installer.sh
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values-v2.yaml

Changes in this PR.
1. updated the dashbase-installer.sh script with two new flags "--indexer_cpu" and "indexer_memory", and this is for changing the indexer cpu/memory requirement.
2. updated the dashbase version to 2.2.11 on both dashbase-installer.sh script and aws_eks_dashbase_install.sh script.
3. updated the aws_eks_dashbase_install.sh script to disable small cluster setup for V2, and by default V2 setup without specify instance type, default will use c5.4xlarge, and without specifying number of nodes, and default is using two nodes.
the changes in this PR is tested using the following command line options
```
./dashbase-installer.sh --platform=aws --ingress \
--bucketname=s3-uhjkootysd \
--subdomain=raytest31.dashbase.io \
--basic_auth --authusername=dashadm …
```

DB-2372 update installer script allow indexer cpu/memory can be changed

---

log-collection/ansible/roles/logstash/templates/configs/sascdr_1.logstash.conf.j2

When JDBC driver reads datetime field from the database, the field type is NOT string, it's a date so 'date' filter conversion fails (it needs a string) and results in _dateparsefailure. We don't need to convert time_start, only copy it into @timestamp.

fix incorrect @timestamp for SAS CDRs logstash configuration

---

dashbase-installer.sh
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/localsetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/localsetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/tinysetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/tinysetup/dashbase-values.yaml
deployment-tools/dashbase-installer-localsetup.sh
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/dashbase-installer-tinysetup.sh
deployment-tools/setup-s3-4v2.sh
deployment-tools/uninstall-dashbase.sh

related to ticket DB-2451 "Add option to enable syslog service and expose tcp load balancer in installer"
1. Added a new flag "--syslog" to enable syslog service via dashbase-installer.sh script.
2. Fixed the etcd_operator check which result in minor error in echo message 
The error `")syntax error: invalid arithmetic operator (error token is "` is caused by newline or carriage return on a numeric variable
3.  Improved all dashbase-installer scripts to support nightly version. Nightly version was error out due to version number variable  `VNUM` is introduced last time. 
4  Updated uninstall-dashbase.sh script to support removal of dashbase syslog deployment set
5. Update `setup-s3-4v2.sh`  S3 bucket creation script to run on both mac and linux
Tested …

DB-2451 enable  syslog via dashbase-installer scripts 

---

dashbase-installer.sh
deployment-tools/check-fed-search.sh
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/localsetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/tinysetup/dashbase-values-v2.yaml
deployment-tools/dashbase-installer-smallsetup.sh
deployment-tools/dashbase-installer-tinysetup.sh

1. update syslog configuration in dashbase-values.yaml file with following env variables
```
SYSLOG_ELASTICSEARCH_HOSTS: https://table-LOGS:7888
```
`SYSLOG_MESSAGE_PARSER` and `SYSLOG_MESSAGE_FORMAT` is currently comment out  and this use case should be explained in wiki page and have customer to enable them..
Added expose_syslog function to expose syslog service using  LB 
2.  Increase the proemtheus pod stateful volume from 10Gi to 20Gi. We find some customers easily fill up prometheus disk. 
3. Added a check-fed-search.sh script, this is a troubleshooting script to easily check federated search health status and provides recommendation when error is detected. And this script should be run in primary dashbase site.
The following is sample script output.

DB-2451 update syslog configuration in dashbase-values.yaml

---

log-collection/ansible/roles/filebeat/templates/configs/avaya.yml

Updated pattern for the latest sample provided by Maintel after they enabled avaya SBC to send data to a rsyslog server.
Sample:
`2020-09-03T17:07:19+01:00 mntl1-vm-sbc1 SSYNDI[3357]: REGISTRATIONS INFO REG 296 SIPRELAY_REGISTRATION:Registration:  Transport Tuple = tls-86.140.3.203:63152=>10.20.24.201:5061, Is Far-end User = Yes, Is a response to Authentication Challenge = No, Subscriber Aor = sips:184549@maintel.co.uk, Number of Bindings = 1:  Binding - 1 = sips:184549@192.168.1.176:63152;expires=3600`
pattern:
`%{TIMESTAMP_ISO8601:timestamp} %{NOTSPACE:system:meta} %{GREEDYDATA:message}`

modified avaya config based on latest sample provided

---

log-collection/ansible/roles/filebeat/templates/configs/kazoo.yml

1. modify `WORD` to `NOTSPACE` when matching `app-group` cuz `app-group` can contain `-`.
2. add an optional space in kazoo parser.
Tested locally.

DB-2720 fix kazoo parsers

---

log-collection/ansible/roles/filebeat/templates/configs/kazoo.yml

Customer provided this feedback:
2020-09-01T14:40:55.155699+00:00 apps001 2600hz[4909]: |SDra93902-e406eca10d7b9f401e4ab94c11ad4c93-06a9h02|kz_services_plans:199(<0.23409.24>) adding plan 36a1a083dd0df9f3b3940b8a972c0e43/762ae31c44a940657f53fd3907a9dc89 for bookkeeper default_bookkeeper
kz_services_plans:199 == erlang file name : line number
(<0.23409.24>) == Erlang PID for the erlang process that is running this code
[4909] == The OS PID of kazoo_apps, or ecallmgr erlang node

rename fields per feedback from the customer

---

log-collection/ansible/roles/filebeat/templates/configs/kazoo.yml
log-collection/ansible/tests/filebeat/configs/kazoo.yml

For freeswitch log like:
2020-09-10 20:33:36.745840 49.20% [DEBUG] sofia.c:10421 IP 74.207.225.214 Approved by acl "trusted[]". Access Granted.
parse percent value  49.20% as double

changed type of percent to double

---

log-collection/ansible/roles/filebeat/templates/configs/freeswitch-nosip.yml
log-collection/ansible/roles/filebeat/templates/configs/freeswitch.yml
log-collection/ansible/roles/filebeat/templates/configs/kazoo.yml
log-collection/ansible/tests/filebeat/configs/freeswitch-nosip.yml
log-collection/ansible/tests/filebeat/configs/freeswitch.yml
log-collection/ansible/tests/filebeat/configs/kazoo.yml

ref: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-close-eof

DB-2842 enable close_eof for freeswitch cdr as cdr files are only updated once

---

log-collection/ansible/roles/filebeat/templates/configs/kazoo.yml
log-collection/ansible/tests/filebeat/configs/kazoo.yml

Example logs:
1. kazoo
```
2020-09-18T09:15:40.380910+00:00 li-123 2600hz[25834]: |0000000000|Undefined:Undefined (emulator) Error in process <0.19222.28> on node ...
```
2. kamailio
```
2020-09-18T07:16:32.275026+00:00 apps001 kamailio[27404]: ERROR: <core> [core/tcp_read.c:1505]: tcp_read_req(): ERROR: tcp_read_req: error reading - c: 0x7f2efe9c35c0 r: 0x7f2efe9c36a8 (-1)
```
Tested locally via dashbase-dev.
Note:
1. I found that the updated pattern for kazoo makes `(emulator) Error in process` unsearchable cuz it's not in any fields. We can discuss and make a better parser for kazoo later (merge the changes for Kamailio firstly) if it's not urgent.
2. I made the `core`(in the above error log) as `module` in the updated parser. (I'm not sure if that's correct)

fix kazoo parsers

---

log-collection/ansible/roles/logstash/tasks/main.yml

Request from Blake at Skyswitch. We used to only read events with event_type='responder' from NetSapiens database.
Blake wants to see more events since they can be useful for troubleshooting. 
This change enables to read all events from NetSapiens database EXCEPT event_type='info'. This was requested.
SELECT statement was changed from:
WHERE event_type='responder'
to:
WHERE event_type!='info'

[DS-674] collect all rows from the table except event_type='info'

---

log-collection/ansible/roles/filebeat/files/fields.yml
log-collection/ansible/roles/filebeat/templates/configs/viber.yml

- first version of the filebeat configuration for viber three CDR types: CSCDR, SBCCDR, SGWCDR
filebeat processors are used to read  CDR data from .csv files, decode data, split csv records into fields, map field names to values, filter some lines based on field values, copy some fields to be present for CDR Call Flows 'common' type.
- update to fields.xml to set new Viber fields as text, except 'ViberToken' which is set to be keyword.

first version of parsing for viber CDRs

---

log-collection/ansible/roles/logstash/tasks/main.yml
log-collection/ansible/roles/logstash/templates/configs/nscdr_1.logstash.conf.j2
log-collection/ansible/roles/logstash/templates/configs/nscdr_2.logstash.conf.j2

- modified SQL query that fetches NSCDRs to use `time_release` - 3seconds to insure records are already updated when they are fetched
- modified nscdr configuration to use `time_release` as a tracking column

Nscdr missing fix

---

dashbase-installer.sh
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values-prod.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values-v2-prod.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/largesetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/localsetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/localsetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/smallsetup/dashbase-values.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/tinysetup/dashbase-values-v2.yaml
deployment-tools/dashbase-admin/dashbase_setup_tarball/tinysetup/dashbase-values.yaml

Background.
Based on ticket https://dashbase.atlassian.net/browse/DB-3432 ; V1 table endpoints can be secured with dashbase `auth` and `INTERNAL_TOKEN`
Changes in this PR.
1. When `--basic_auth` flag is used in Install script, `INTERNAL_TOKEN` string will automatically appended in dashbase-values.yaml file under the  default v1 table env variables;   when `--basic_auth` flag is used .
2. Remove presto TLS cert creation when presto is not enabled
3. Remove LF (line feed) `^M`  trailing at the license string and TOKEN string, that is because `cat` command automatically have  line feed inserted.
Tested the default install with following command
```
./dashbase-installer.sh --platform=aws --ingress \
--v1 \
--subdomain=raydash1218c.dashbase.io \
--basic_auth --version=2.5.5 \ …
```

DB-3483 Add support for table token during installation
